name = "ip-please"
default_targets = ["win32", "win64", "macos"]
build_directory = "release"
icon_file = "icon.png"

love_files = [
    "*.lua",
    "*.ttf",
    "*.txt",
    "*.glsl",
    "*.ogg"
]

[hooks]
prebuild = [
    "clue src -t=luajit"
]
